In [3]:
import numpy as np

In [7]:
w1 = np.random.randn(2,2) * 0.01 # 生成高斯分布
b1 = np.zeros((2,1))
w2 = np.random.randn(2,2) * 0.01
b2 = np.zeros((2,1))
print("{}".format(w1))
print("{}".format(b1))
print("{}".format(w2))
print("{}".format(b2))

[[-0.00152691  0.00140834]
 [-0.00339649 -0.01026983]]
[[0.]
 [0.]]
[[ 0.00785775 -0.00242643]
 [-0.00866492 -0.01759895]]
[[0.]
 [0.]]
