In [5]:
import math
def basic_sigmoid(x):
    s = 1 / (1 + math.exp(-x))
    return s

In [7]:
basic_sigmoid(3)

0.9525741268224334

In [17]:
import numpy as np
x = np.array([1,2,3])

In [9]:
x

array([1, 2, 3])

In [10]:
print(x+3) #broadcasting

[4 5 6]


**练习1**：使用numpy实现sigmoid函数。
说明：x可以是实数，向量或矩阵。 我们在numpy中使用的表示向量、矩阵等的数据结构称为numpy数组。现阶段你只需了解这些就已足够。

In [15]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [12]:
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [19]:
y = np.array([-1,-0.5,0,0.5,1])
sigmoid(y)

array([0.26894142, 0.37754067, 0.5       , 0.62245933, 0.73105858])

In [15]:
z = 1
sigmoid(z)

0.7310585786300049

**练习2**： 创建函数sigmoid_grad（）计算sigmoid函数相对于其输入x的梯度。公式为：s=a*(1-a)

In [8]:
def sigmoid_derivative(x):
    s = 1 / (1 + np.exp(-x))
    return s*(1-s)

In [10]:
print("进行计算")

进行计算


In [20]:
print("向量x的sigmod:"+str(sigmoid(y)))
      
print("向量x的梯度:"+str(sigmoid_derivative(y)))

向量x的sigmod:[0.26894142 0.37754067 0.5        0.62245933 0.73105858]
向量x的梯度:[0.19661193 0.23500371 0.25       0.23500371 0.19661193]


## 修改数组形状
例如，在计算机科学中，图像由shape为(length,height,depth=3)的3D数组表示。但是，当你读取图像作为算法的输入时，会将其转换为维度为(lenght*height*3,1)的向量。换句话说，将3D阵列“展开”或重塑为1D向量。



**练习3**：
实现image2vector() ,该输入采用维度为(length, height, 3)的输入，并返回维度为(length*height*3, 1)的向量。例如，如果你想将形为（a，b，c）的数组v重塑为维度为(a*b, 3)的向量，则可以执行以下操作：

v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c


In [23]:
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    shape  = image.shape
    v = image.reshape(shape[0]*shape[1]*shape[2],1)
    return v

In [28]:
image = np.array(
    [
        #第一层
        [
            #第一行
            [ 0.67826139,  0.29380381],
            #第二行
            [ 0.90714982,  0.52835647],
            #第三行
            [ 0.4215251 ,  0.45017551]
        ],
        #第二层
       [
           [ 0.92814219,  0.96677647],
            [ 0.85304703,  0.52351845],
            [ 0.19981397,  0.27417313]
       ],
        #第三层
       [
        [ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]
       ]
    ]
)
#转换成列向量
res = image2vector(image)
print ("image2vector(image) = " + str(res)) # n*1
print("res:"+str(res.T)) # 1*n

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
res:[[0.67826139 0.29380381 0.90714982 0.52835647 0.4215251  0.45017551
  0.92814219 0.96677647 0.85304703 0.52351845 0.19981397 0.27417313
  0.60659855 0.00533165 0.10820313 0.49978937 0.34144279 0.94630077]]


## 行标准化
我们在机器学习和深度学习中使用的另一种常见技术是对数据进行标准化。 由于归一化后梯度下降的收敛速度更快，通常会表现出更好的效果。 通过归一化，也就是将x更改为（将x的每个行向量除以其范数）。

### 练习
执行 normalizeRows（）来标准化矩阵的行。 将此函数应用于输入矩阵x之后，x的每一行应为单位长度（即长度为1）向量。

In [29]:
def normalizeRows(x):
    norm = np.linalg.norm(x,axis=1,keepdims=True)
    x = x/norm
    return x

In [32]:
x = [
    [1,2,3],
    [0,4,3]
]
print("res:"+str(normalizeRows(x)))

res:[[0.26726124 0.53452248 0.80178373]
 [0.         0.8        0.6       ]]


### 注意：
在normalizeRows（）中，你可以尝试print查看 x_norm和x的维度，然后重新运行练习cell。 你会发现它们具有不同的w维度。 鉴于x_norm采用x的每一行的范数，这是正常的。 因此，x_norm具有相同的行数，但只有1列。 那么，**当你将x除以x_norm时，它是如何工作的？** 这就是所谓的广播broadcasting，我们现在将讨论它！

In [39]:
def normalizeRows2(x):
    # 求横轴范数
    norm = np.linalg.norm(x,axis=1,keepdims=True)
    x = x/norm
    print("norm.shape:"+str(norm.shape))
    print("x.shape:"+str(x.shape))
    return x
x = [
    [1,2,3],
    [0,4,3]
]
print("res2:"+str(normalizeRows2(x)))

print("#换下轴试一下")
def normalizeRows3(x):
    # 求纵轴范数
    norm = np.linalg.norm(x,axis=0,keepdims=True)
    x = x/norm
    print("norm.shape:"+str(norm.shape))
    print("x.shape:"+str(x.shape))
    return x
print("res3:"+str(normalizeRows3(x)))


norm.shape:(2, 1)
x.shape:(2, 3)
res2:[[0.26726124 0.53452248 0.80178373]
 [0.         0.8        0.6       ]]
#换下轴试一下
norm.shape:(1, 3)
x.shape:(2, 3)
res3:[[1.         0.4472136  0.70710678]
 [0.         0.89442719 0.70710678]]


## 广播和softmax函数
在numpy中要理解的一个非常重要的概念是“广播”。 这对于在不同形状的数组之间执行数学运算非常有用。 有关广播的完整详细信息，你可以阅读官方的broadcasting documentation.

### 练习:
使用numpy实现softmax函数。 你可以将softmax理解为算法需要对两个或多个类进行分类时使用的标准化函数。 你将在本专业的第二门课中了解有关softmax的更多信息。

In [44]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp,axis=1,keepdims=True)
    s = x_exp/x_sum
    return s
xs = [
    [1,2,3],
    [4,5,0]
]
xs_softmax = softmax(xs)
print(str(xs_softmax))

[[0.09003057 0.24472847 0.66524096]
 [0.26762315 0.72747516 0.00490169]]


## 向量化
在深度学习中，通常需要处理非常大的数据集。 因此，非计算最佳函数可能会成为算法中的巨大瓶颈，并可能使模型运行一段时间。 为了确保代码的高效计算，我们将使用向量化。 例如，尝试区分点/外部/元素乘积之间的区别。

In [48]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.10406299999998758ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [52]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.13271900000000336ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.14455400000001895ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.1147249999999822ms
gdot = [27.98533902 24.95128314 19.9442907

## 实现L1和L2损失函数

In [54]:
def L1(yhat,y):
    loss = np.sum(np.abs(yhat-y))
    return loss

yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L1:"+str(L1(yhat,y)))


L1:1.1


In [55]:
def L2(yhat,y):
    return np.dot((y-yhat),(y-yhat).T)

yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L2:"+str(L2(yhat,y)))

L2:0.43
